apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacedeck
  namespace: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacedeck
  template:
    metadata:
      labels:
        app: spacedeck
    spec:
      initContainers:
        - name: init-db
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /data
              if [ ! -f /data/database.sqlite ]; then
                touch /data/database.sqlite
                chmod 666 /data/database.sqlite
              fi
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: spacedeck
          image: akito13/spacedeck:latest
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: data
              mountPath: /app/database.sqlite
              subPath: database.sqlite
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spacedeck-data