apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: draw
  labels:
    app: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: frontend
          image: excalidraw/excalidraw:latest
          ports:
            - containerPort: 80
        - name: collab-server
          image: excalidraw/excalidraw-room:latest
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000