apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-frontend
  namespace: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-frontend
  template:
    metadata:
      labels:
        app: excalidraw-frontend
    spec:
      containers:
        - name: excalidraw
          image: excalidraw/excalidraw:latest
          ports:
            - containerPort: 80