apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: draw-ingress
  namespace: draw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`draw.awspythoncourses.org`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: draw-oauth
      services:
        - name: excalidraw-backend
          port: 5000

    - match: Host(`draw.awspythoncourses.org`) && PathPrefix(`/socket.io`)
      kind: Rule
      middlewares:
        - name: draw-oauth
      services:
        - name: excalidraw-backend
          port: 5000

    - match: Host(`draw.awspythoncourses.org`) && PathPrefix(`/oauth2`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 4180

    - match: Host(`draw.awspythoncourses.org`)
      kind: Rule
      middlewares:
        - name: draw-oauth
      services:
        - name: excalidraw-frontend
          port: 80

  tls:
    secretName: draw-tls