apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: excalidraw-ingress
  namespace: draw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`draw.awspythoncourses.org`) && PathPrefix(`/socket.io/`)
      services:
        - name: excalidraw
          port: 3000
          protocol: http
    - kind: Rule
      match: Host(`draw.awspythoncourses.org`)
      services:
        - name: excalidraw
          port: 4180
          protocol: http
  tls:
    secretName: draw-tls