apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spacedeck-ingress
  namespace: draw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`board.awspythoncourses.org`)
      kind: Rule
      middlewares:
        - name: draw-oauth
      services:
        - name: spacedeck
          port: 9666
  tls:
    secretName: draw-tls
