apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spacedeck-ingress
  namespace: draw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`draw.awspythoncourses.org`)
      kind: Rule
      services:
        - name: spacedeck
          port: 4180
  tls:
    secretName: draw-tls
