apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          args:
            - --provider=google
            - --http-address=0.0.0.0:4180
            - --redirect-url=https://draw.awspythoncourses.org/oauth2/callback
            - --email-domain=gmail.com
            - --authenticated-emails-file=/etc/oauth2/authenticated-emails.txt
            - --cookie-secret=$(OAUTH2_COOKIE_SECRET)
            - --client-id=$(OAUTH2_CLIENT_ID)
            - --client-secret=$(OAUTH2_CLIENT_SECRET)
            - --upstream=http://spacedeck:9666
          envFrom:
            - secretRef:
                name: oauth2-secret
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: email-list
              mountPath: /etc/oauth2
              readOnly: true
      volumes:
        - name: email-list
          configMap:
            name: oauth2-allowed-emails