apiVersion: v1
kind: Service
labels:
  app: oauth2-proxy
metadata:
  name: oauth2-proxy
  namespace: draw
labels:
  app: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - protocol: TCP
      port: 4180
      targetPort: 4180
  type: ClusterIP