apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tldraw-data
  namespace: draw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path