apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: draw
spec:
  selector:
    app: excalidraw
  ports:
    - name: web
      port: 4180
      targetPort: 80
    - name: ws
      port: 3002
      targetPort: 3000