---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-frontend
  namespace: draw
spec:
  selector:
    app: excalidraw-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-backend
  namespace: draw
spec:
  selector:
    app: excalidraw-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: draw
spec:
  selector:
    app: oauth2-proxy
  ports:
    - protocol: TCP
      port: 4180
      targetPort: 4180